# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('youtube', 'YouTube'), ('audio', 'Audio')], default='image', max_length=140)),
                ('filename', models.CharField(default='20160904/1.jpg', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='announce_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.Post'),
        ),
    ]
